{-# LANGUAGE TemplateHaskell #-}
module Zwirn.Interactive.Generic where

import Language.Haskell.TH
import Zwirn.Interactive.Types (P, NumberPattern, TextPattern, ControlPattern)
import Zwirn.Interactive.Transform (_toPat)
import Zwirn.Interactive.Convert (_toTarget)
import qualified Prelude as P

_mkStringParams :: [P.String] -> Q [Dec]
_mkStringParams names = P.return (P.map oneDec names P.++ P.map sig names)
                  where oneDec name = ValD (VarP (mkName name)) (NormalB (AppE (VarE '_toPat) (AppE (VarE '_toTarget) (VarE (mkName ("T." P.++ name)))))) []
                        sig name = SigD (mkName name) (AppT (ConT ''P) (AppT (AppT ArrowT (ConT ''TextPattern)) (ConT ''ControlPattern)))

_mkNumParams :: [P.String] -> Q [Dec]
_mkNumParams names = P.return (P.map oneDec names P.++ P.map sig names)
                  where oneDec name = ValD (VarP (mkName name)) (NormalB (AppE (VarE '_toPat) (AppE (VarE '_toTarget) (VarE (mkName ("T." P.++ name)))))) []
                        sig name = SigD (mkName name) (AppT (ConT ''P) (AppT (AppT ArrowT (ConT ''NumberPattern)) (ConT ''ControlPattern)))

_stringParams :: [P.String]
_stringParams = ["s","unit","vowel","sound","toArg"]

_numParams :: [P.String]
_numParams = ["accelerate"
            ,"amp"
            ,"attack"
            ,"bandf"
            ,"bandq"
            ,"begin"
            ,"binshift"
            ,"ccn"
            ,"ccv"
            ,"channel"
            ,"coarse"
            ,"comb"
            ,"cps"
            ,"crush"
            ,"cut"
            ,"cutoff"
            ,"decay"
            ,"delay"
            ,"delaytime"
            ,"detune"
            ,"distort"
            ,"djf"
            ,"dry"
            ,"dur"
            ,"end"
            ,"enhance"
            ,"expression"
            ,"fadeInTime"
            ,"fadeTime"
            ,"freeze"
            ,"freq"
            ,"from"
            ,"fshift"
            ,"gain"
            ,"gate"
            ,"harmonic"
            ,"hbrick"
            ,"hcutoff"
            ,"hold"
            ,"hresonance"
            ,"imag"
            ,"krush"
            ,"lagogo"
            ,"lbrick"
            ,"legato"
            ,"leslie"
            ,"lock"
            ,"midibend"
            ,"miditouch"
            ,"modwheel"
            ,"n"
            ,"note"
            ,"nudge"
            ,"octave"
            ,"octer"
            ,"octersub"
            ,"octersubsub"
            ,"offset"
            ,"orbit"
            ,"overgain"
            ,"overshape"
            ,"pan"
            ,"panorient"
            ,"panspan"
            ,"pansplay"
            ,"panwidth"
            ,"partials"
            ,"phaserdepth"
            ,"phaserrate"
            ,"rate"
            ,"real"
            ,"release"
            ,"resonance"
            ,"ring"
            ,"ringdf"
            ,"ringf"
            ,"room"
            ,"sagogo"
            ,"scram"
            ,"shape"
            ,"size"
            ,"slide"
            ,"smear"
            ,"speed"
            ,"squiz"
            ,"stutterdepth"
            ,"stuttertime"
            ,"sustain"
            ,"sustainpedal"
            ,"timescale"
            ,"timescalewin"
            ,"to"
            ,"tremolodepth"
            ,"tremolorate"
            ,"triode"
            ,"tsdelay"
            ,"velocity"
            ,"voice"
            ,"waveloss"
            ,"xsdelay"
            ,"voi"
            ,"up"
            ,"tremr"
            ,"tremdp"
            ,"sz"
            ,"sus"
            ,"stt"
            ,"std"
            ,"sld"
            ,"scr"
            ,"rel"
            ,"por"
            ,"phasr"
            ,"phasdp"
            ,"number"
            ,"lpq"
            ,"lpf"
            ,"hpq"
            ,"hpf"
            ,"gat"
            ,"fadeOutTime"
            ,"dt"
            ,"dfb"
            ,"det"
            ,"delayt"
            ,"delayfb"
            ,"ctf"
            ,"bpq"
            ,"bpf"
            ,"att"
            ]
