editor:
  port: 8023
  highlight: false
  bootpath: ""

stream:
  port: 57120
  address: "127.0.0.1"

clock:
  quantum: 4
  beatspercycle: 4
  frametimespan: 0.05
  enablelink: false
  skipticks: 10
  processahead: 0.3
